# Generated by Django 4.2.7 on 2025-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_chatsession_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
